[cse]
type = sftp
host = login.cse.unsw.edu.au
user = z5555555
key_use_agent = true
shell_type = unix
known_hosts_file = ~/.ssh/known_hosts
key_file = ~/.ssh/id_ed25519
md5sum_command = md5sum
sha1sum_command = sha1sum