return {
  "petertriho/nvim-scrollbar",
  dependencies = { "lewis6991/gitsigns.nvim" },
  event = "BufReadPost",
  opts = {
    show_in_active_only = true,
    hide_if_all_visible = false,
    throttle_ms = 16,
    handle = {
      hide_if_all_visible = true,
      color = "#989eb6",
      blend = 0,
    },
    handlers = {
      cursor = false,
      diagnostic = true,
      gitsigns = true,
      handle = true,
      search = false,
    },
    excluded_filetypes = {
      "blink-cmp-menu",
      "dropbar_menu",
      "dropbar_menu_fzf",
      "DressingInput",
      "cmp_docs",
      "cmp_menu",
      "noice",
      "prompt",
      "TelescopePrompt",
      "snacks_dashboard",
      "snacks_picker_list",
      "snacks_picker_input",
      "snacks_notif",
      "lazy",
      "mason",
      "trouble",
    },
  },
}
