# Terminal colour support
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-ghostty:RGB"

# Preserve colour capability for programs inside tmux
set-environment -g COLORTERM truecolor

# Close the active pane with Ctrl+b, x
unbind-key x
bind-key x confirm-before -p "kill-pane #{pane_index}? (y/n)" kill-pane

# Enable mouse control
set -g mouse on

# True colours for claude code
set-environment -g CLAUDE_CODE_TMUX_TRUECOLOR true

# Window naming
set -g @catppuccin_window_text "#{pane_current_command}"
set -g @catppuccin_window_current_text "#{pane_current_command}"

# DESIGN TWEAKS

# Load Catppuccin
set -g @catppuccin_flavor 'mocha'
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Status line
set -g status-left ""
set -g status-right '%H:%M %d-%b-%y'
