# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# Window naming
set -g @catppuccin_window_text "#{pane_current_command}"
set -g @catppuccin_window_current_text "#{pane_current_command}"

# DESIGN TWEAKS

# Load catppuccin
set -g @catppuccin_flavor 'mocha'
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Status line
set -g status-left ""
set -g status-right '%H:%M %d-%b-%y'
