# Terminal colour support
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-ghostty:RGB"

# Preserve colour capability for programs inside tmux
set-environment -g COLORTERM truecolor

# Forward extended key sequences
set -s extended-keys always
set -as terminal-features 'xterm*:extkeys'

# Allow passthrough for notifications and progress bars
set -g allow-passthrough on

# Close the active pane with Ctrl+b, x
unbind-key x
bind-key x confirm-before -p "kill-pane #{pane_index}? (y/n)" kill-pane

# Enable mouse control
set -g mouse on

# True colours for claude code
set-environment -g CLAUDE_CODE_TMUX_TRUECOLOR true

# DESIGN TWEAKS

# Load Catppuccin
set -g @catppuccin_flavor 'mocha'
source -F ~/.config/tmux/plugins/catppuccin/tmux/catppuccin_options_tmux.conf
source -F ~/.config/tmux/plugins/catppuccin/tmux/catppuccin_tmux.conf

# Status bar
set -g @bar_bg "default"
set -g status-interval 1
set -g status-position top
set -g status-justify left
set -gF status-style "bg=#{@bar_bg},fg=#{@thm_fg}"

# Window list
set -gF window-status-style "bg=#{@bar_bg},fg=#{@thm_fg}"
set -gF window-status-current-style "bg=#{@thm_mauve},fg=#{@thm_crust},bold"
set -g window-status-separator ""
set -g window-status-format " #I: #{s/^[0-9]+\\.[0-9]+\\.[0-9]+$/claude/:pane_current_command} "
set -g window-status-current-format " #I: #{s/^[0-9]+\\.[0-9]+\\.[0-9]+$/claude/:pane_current_command} "

# Session name on the left
set -g status-left "#[fg=#{E:@thm_crust},bg=#{?client_prefix,#{E:@thm_red},#{E:@thm_sapphire}},bold] #S #[fg=#{E:@thm_fg},bg=#{E:@bar_bg},nobold]"
set -g status-left-length 40

# Time and date on the right
set -g status-right "#[fg=#{E:@thm_fg},bg=#{E:@bar_bg}] %-I:%M %p #[fg=#{E:@thm_crust},bg=#{E:@thm_sapphire},bold] %d/%m/%Y "
set -g status-right-length 40

# Panes
set -gF pane-border-style "fg=#{@thm_overlay_0}"
set -gF pane-active-border-style "fg=#{@thm_lavender}"

# Copy mode
set -gF mode-style "bg=#{@thm_surface_2},fg=#{@thm_fg},bold"
set -wgF copy-mode-match-style "bg=#{@thm_surface_2},fg=#{@thm_fg}"
set -wgF copy-mode-current-match-style "bg=#{@thm_green},fg=#{@thm_crust}"
