# cp .dotter/local.example.toml .dotter/local.toml
# dotter deploy

packages = ["ghostty", "nvim", "zsh", "tmux", "git", "rclone", "vscodium", "obsidian", "homebrew", "kitty", "bat", "ccstatusline", "neovide", "linearmouse", "lazygit"]

[variables]
zid = "z0000000"
